[workspace]
members = [
    "leaf",
    "leaf-bin",
    "leaf-ffi",
    "leaf-plugins/shadowsocks",
]
default-members = ["leaf-bin"]

[profile.release]
opt-level = 3
lto = true
# codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
opt-level = 0
debug = true
