[package]
name = "leaf"
version = "0.1.2"
authors = ["eycorsican <eric.y.corsican@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "leaf"
path = "src/lib.rs"

[features]
default = [
    "default-ring"
]

default-ring = [
    "all-configs",
    "all-endpoints",
    "ring-aead",
    "rustls-tls",
	# quinn supports only rustls as tls backend for now
    "inbound-quic",
    "outbound-quic",
    "api",
]

default-openssl = [
    "all-configs",
    "all-endpoints",
    "openssl-aead",
    "openssl-tls",
    "api",
]

# Grouping all features
all-configs = [
    "config-conf",
    "config-json",
]
all-endpoints = [
    # inbounds
    "inbound-chain",
    "inbound-amux",
    # "inbound-quic",
    "inbound-ws",
    "inbound-trojan",
    "inbound-http",
    "inbound-shadowsocks",
    "inbound-socks",
    "inbound-tun",
    # outbounds
    "outbound-direct",
    "outbound-drop",
    "outbound-redirect",
    "outbound-shadowsocks",
    "outbound-socks",
    "outbound-trojan",
    "outbound-vmess",
    "outbound-tls",
    "outbound-ws",
    "outbound-amux",
    # "outbound-quic",
    "outbound-h2",
    "outbound-failover",
    "outbound-random",
    "outbound-tryall",
    "outbound-chain",
    "outbound-retry",
    "outbound-select",
]

# Ring-related
ring-aead = ["ring"]
rustls-tls = ["tokio-rustls", "webpki-roots"]

# Openssl-related, for platforms not supported by ring, such as mips
openssl-aead = ["openssl"]
openssl-tls = ["openssl", "tokio-openssl", "openssl-probe"]

# Config formats
config-conf = ["regex"]
config-json = ["serde", "serde_derive", "serde_json"]

# Outbounds
outbound-direct = []
outbound-drop = []
outbound-redirect = []
outbound-shadowsocks = ["hkdf", "sha-1", "md-5", "tokio-util"]
outbound-socks = ["async-socks5"]
outbound-trojan = ["sha2", "hex"]
outbound-vmess = ["lz_fnv", "cfb-mode", "hmac", "aes", "sha3", "digest", "uuid", "md-5", "tokio-util"]
outbound-tls = []
outbound-ws = ["tungstenite", "tokio-tungstenite", "url", "http"]
outbound-h2 = ["h2", "http", "url"]
outbound-failover = ["lru_time_cache"]
outbound-random = []
outbound-tryall = []
outbound-chain = []
outbound-retry = []
outbound-amux= ["tokio-util"]
outbound-quic = ["quinn", "rustls", "webpki-roots"]
outbound-select = []

# Inbounds
inbound-trojan = ["sha2", "hex"]
inbound-shadowsocks = ["hkdf", "sha-1", "md-5", "tokio-util"]
inbound-socks = []
inbound-http = ["hyper"]
inbound-tun = ["tun"]
inbound-ws = ["tungstenite", "tokio-tungstenite", "url", "http"]
inbound-amux = ["tokio-util"]
inbound-quic = ["quinn", "rustls", "webpki-roots"]
inbound-chain = []

api = ["warp"]
auto-reload = ["notify"]
ctrlc = ["tokio/signal"]

[dependencies]
# Common
tokio = { version = "1", features = ["sync", "io-util", "net", "time", "rt", "rt-multi-thread"] }
futures-util = "0.3"
protobuf = "2"
thiserror = "1.0"
futures = "0.3"
async-trait = "0.1"
byteorder = "1"
bytes = "1"
lazy_static = "1.4.0"
anyhow = "1.0"
rand = "0.8"
socket2 = "0.4"
directories = "3.0"

# config-json
serde_json = { version = "1.0", features = ["raw_value"], optional = true }
serde_derive = { version = "1.0", optional = true }
serde = { version = "1.0", optional = true }

# config-conf
regex = { version = "1", default-features = false, features = ["std", "perf"], optional = true }

# Openssl
openssl = { version = "0.10", features = ["vendored"], optional = true }

# Ring
ring = { version = "0.16", optional = true }

# Router
maxminddb = { version = "0.17", features = ["mmap"] }
memmap = "0.7"
cidr = { version = "0.1", default-features = false }

# DNS
trust-dns-proto = { version = "0.20", default-features = false }
lru = "0.6"

# Logging
log = { version = "0.4", features = ["std"] }
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4"
colored = "2.0"

# TLS/rustls/QUIC
tokio-rustls = { version = "0.22", optional = true }
webpki-roots = { version = "0.21", optional = true }

# TLS/openssl
openssl-probe = { version = "0.1", optional = true }
tokio-openssl = { version = "0.6", optional = true }

# WebSocket
tungstenite = { version = "0.13", default-features = false, optional = true }
tokio-tungstenite = { version = "0.14", optional = true }

# WebSocket/HTTP/2
url = { version = "2.2", optional = true }

# HTTP inbound
hyper = { version = "0.14", default-features = false, features = ["server", "http1"], optional = true }

# HTTP/2
h2 = { version = "0.3", features = ["stream"], optional = true }
http = { version = "0.2", optional = true }

# SOCKS outbound
async-socks5 = { version = "0.5", optional = true }

# VMess
lz_fnv = { version = "0.1", optional = true }
cfb-mode = { version = "0.6", optional = true }
hmac = { version = "0.10", optional = true }
aes = { version = "0.6", optional = true }
sha3 = { version = "0.9", optional = true }
digest = { version = "0.9", optional = true }

# VMess
uuid = { version = "0.8", optional = true }

# VMess/Shadowsocks
md-5 = { version = "0.9", optional = true }

# Shadowsocks
hkdf = { version = "0.10", optional = true }
sha-1 = { version = "0.9", optional = true }

# Trojan
sha2 = { version = "0.9", optional = true }
hex = { version = "0.4", optional = true }

# Failover
lru_time_cache = { version = "0.11", optional = true }

# amux
tokio-util = { version = "0.6", default-features = false, features = ["io"], optional = true }

# QUIC
quinn = { version = "0.7", default-features = false, features = ["tls-rustls"], optional = true }
rustls = { version = "0.19", optional = true }

# API
warp = { version = "0.3", default-features = false, optional = true }

# Auto reload
notify = { version = "5.0.0-pre.6", optional = true }

# TUN
[target.'cfg(any(target_os = "ios", target_os = "android", target_os = "macos", target_os = "linux"))'.dependencies]
tun = { git = "https://github.com/eycorsican/rust-tun.git", branch = "upgrade", features = ["async"], optional = true }

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
pnet_datalink = { version = "0.27", package = "pnet_datalink" }
libc = "0.2"

# Used in mobile logger
[target.'cfg(any(target_os = "ios", target_os = "macos", target_os = "android"))'.dependencies]
memchr = { version = "2" }

[dev-dependencies]
rcgen = "0.8"

[build-dependencies]
cc = "1.0"
bindgen = "0.58"
protoc-rust = "2"
